name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  short:
    name: Short tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev and xorg-dev

    - name: Setup Windows Dependencies
      if: runner.os == 'Windows'
      run: |
        choco install -y make mingw

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Run Tests
      run: make check
      env:
        GOTEST_FLAGS: "-short"

  sources-long:
    name: Long testing pkg/sources/
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Short Tests
      run: go test ./pkg/sources... -count 1 -v

  docker:
    name: Docker build
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Setup Node / NPM
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Docker Build
      run: make docker-hub

  webui:
    name: Build Webui
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup fyne
      run: make setup-webui

    - name: Build Webui
      run: make build-webui

    - name: Docker Build
      run: make docker-webui
